### ISSUE TITLE
📝 Issue: Checkout 페이지 레이아웃 및 CSS

### ISSUE THREAD

**Issue by soyoung931014** [soyoung931014/colavo_assignment#4]
## ISSUE
- Group: `client`
- Type: `feature`, css` 
- Detail: Checkout 페이지, 해당 페이지 관련 컴포넌트 생성, 레이아웃 및 css

## TODO
- [x] Button 레이아웃 및 css
- [x] TitleBar 레이아웃 및 css
- [x] Modal 생성
- [x] Checkout 페이지 레이아웃 및 css
